# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MasonX-Request-HTMLTemplate
version:      0.06
version_from: HTMLTemplate.pm
installdirs:  site
requires:
    File::Spec:                    0
    HTML::Mason:                   1.16
    HTML::Template::Extension:     0.23
    Params::Validate:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
